apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: node-metrics
spec:
  image: otel/opentelemetry-collector-contrib:0.119.0
  mode: daemonset
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  volumes:
    - name: hostfs
      hostPath:
        path: / 
        type: Directory
  volumeMounts:
    - name: hostfs
      mountPath: /host
      readOnly: true
      mountPropagation: HostToContainer
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: ingress-nginx
            metrics_path: /metrics
            static_configs:
            - targets: ['ingress-nginx-controller-metrics.ingress-nginx.svc:10254']
      kubeletstats:
        collection_interval: 20s
        auth_type: "serviceAccount"
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
    exporters:
      prometheusremotewrite:
        endpoint: http://prometheus-server.prometheus.svc.cluster.local:80/api/v1/write
    service:
      pipelines:
        metrics:
          receivers: [prometheus, kubeletstats]
          exporters: [prometheusremotewrite]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-kubelet-stats
rules:
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/proxy"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-kubelet-stats
subjects:
  - kind: ServiceAccount
    name: node-metrics-collector
    namespace: opentelemetry-operator-system
roleRef:
  kind: ClusterRole
  name: otel-collector-kubelet-stats
  apiGroup: rbac.authorization.k8s.io