apiVersion: v2
name: ingress-nginx-wrapper
description: A wrapper chart for ingress-nginx
type: application
version: 0.1.0
appVersion: "1.14.3"

dependencies:
  - name: ingress-nginx
    version: 4.14.3
    repository: https://kubernetes.github.io/ingress-nginx
